# Copyrihgt (C) 2023 M4TRIX04 
# 
#
# Copyright (C) 2019 P3TERX
# <https://github.com/P3TERX/Actions-OpenWrt>

# Copyright (C) 2020 KFERMercer
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Build x86_OpenWrt

on:
  workflow_dispatch:
    inputs:
      Repo:
        required: true
        type: choice
        options:
        - https://github.com/immortalwrt/immortalwrt
        - https://github.com/coolsnowwolf/lede
        - https://github.com/openwrt/openwrt
      Branch:
        required: true
        type: choice
        options:
        - master
        - openwrt-23.05
        - openwrt-21.02
     
env:
  REPO_URL: ${{ inputs.Repo }}
  REPO_BRANCH: ${{ inputs.Branch }}
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: x86.config
  DIY_P1_SH: x86.sh
  DIY_P2_SH: custom-2.sh
  UPLOAD_BIN_TARGETS: true
  UPLOAD_BIN_PACKAGES: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: 检查服务器配置
      run: |
        echo "警告⚠"
        echo "若分配的服务器性能不足，务必及时取消，重新运行！"
        echo "已知编译成功CPU型号：8370C,8171M"
        echo "已知性能不足CPU型号：8272CL"
        echo -e "-------------- ------------CPU信息------------------------------------------\n"
        echo "CPU物理数量:$(cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l)"
        echo -e "CPU核心及版本信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo "-------------------------------内存信息-------------------------------------------"
        echo "已安装内存详细信息："
        sudo lshw -short -C memory | grep GiB
        echo -e "\n"
        echo "-----------------------------硬盘信息---------------------------------------------"
        echo -e  "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l) \n"
        echo "硬盘详情："
        df -Th

    - name: 安装编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        
    - name: 下载固件源码
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        cd ./openwrt
        useVersionInfo=$(git show -s --date=short --format="%0AAuthor: %an%0Adate: %cd%0Acommit: %s%0Acommit hash: %H")
        echo "useVersionInfo=$useVersionInfo" >> $GITHUB_ENV
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        
    - name: 加载自定义设置
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF ./openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd ./openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH
        
        
    - name: 下载插件
      run: |
        ./openwrt/scripts/feeds update -a
        rm -fr /openwrt/feeds/luci/applications/luci-app-passwall
        ./openwrt/scripts/feeds update -a
        ./openwrt/scripts/feeds install -a

    - name: 更改设置
      run: |
        [ -e files ] && mv files ./openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE ./openwrt/.config
        chmod +x $DIY_P2_SH
        cd ./openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH
        
    - name: 下载安装包
      id: package
      run: |
        cd ./openwrt
        make defconfig
        make download -j8 V=s
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: 开始编译固件
      id: compile
      run: |
        cd ./openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        echo "TAG_TIME=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV
        
    - name: 查看磁盘使用情况
      if: (!cancelled())
      run: df -hT

    - name: 上传bin_targets压缩目录
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_TARGETS == 'true'
      with:
        name: OpenWrt_bin_targets_${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ./openwrt/bin/targets/
        
    - name: 上传bin_packages压缩目录
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_PACKAGES == 'true'
      with:
        name: OpenWrt_bin_packages_${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ./openwrt/bin/packages/

    - name: 整理编译好的固件
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd ./openwrt/bin/targets/*/*
        rm -rf packages/
        zip -qr Packages.zip $(find $GITHUB_WORKSPACE/openwrt/bin/packages/ -type f -name "*.ipk")
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: 创建release标签
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=${{ env.TAG_TIME }}" >> $GITHUB_OUTPUT
        touch release.txt
        cat >> release.txt <<EOF
        Repository: ${{ inputs.Repo }}/tree/${{ inputs.Branch }}
        Default IP: 10.0.0.1
        Default username: root
        Default password: password
        Default WIFI name: OpenWrt
        Default WIFI password: none
        Default Theme: ArgonTheme
        Application: autoreboot, ddns(cloudflare-v4), filetransfer, firewall, passwall(ss-libev-s, ss-rust-s, ss-rust-c, trojan-plus, ipt2socks), vlmcsd, wol
        EOF
        echo "status=success" >> $GITHUB_OUTPUT
                
    - name: 发布至release
      uses: softprops/action-gh-release@v2
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        name: ${{ env.TAG_TIME }}-${{ env.DEVICE_NAME }}
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 180
        keep_minimum_runs: 10
        
    - name: Remove old Releases 
      uses: dev-drprasad/delete-older-releases@v0.3.4
      with:
        keep_latest: 10
        delete_tag_pattern: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
